import React,{useState}from"react";
import{SafeAreaView,View,Text,StyleSheet,Pressable,ScrollView,TextInput,StatusBar,Modal}from"react-native";
type Lang="ru"|"tj";type Tab="home"|"academy"|"terminal"|"tools"|"profile";
const tx={ru:{home:"Главная",academy:"Академия",terminal:"Терминал",tools:"Инструменты",profile:"Профиль",sub:"Система обучения трейдингу",demo:"Демо-счёт",learn:"Продолжить обучение",market:"Рынок",buy:"BUY",sell:"SELL",risk:"Risk Calculator",journal:"Trading Journal",plan:"Trading Plan",progress:"Прогресс",author:"JABORZODA and MUZAFARZODA"},tj:{home:"Асосӣ",academy:"Академия",terminal:"Терминал",tools:"Асбобҳо",profile:"Профил",sub:"Системаи омӯзиши трейдинг",demo:"Ҳисоби демо",learn:"Идомаи омӯзиш",market:"Бозор",buy:"BUY",sell:"SELL",risk:"Risk Calculator",journal:"Trading Journal",plan:"Trading Plan",progress:"Пешрафт",author:"JABORZODA and MUZAFARZODA"}};
const modules=["Forex Basics","Market Structure","Candlestick Analysis","Support & Resistance","Indicators","Risk Management","Trading Psychology","Strategy Building","Backtesting","Trading Plan","Trading Journal","Final Test"];
const candles=[35,52,44,68,59,76,66,84,72,91,80,105,94,112];
export default function App(){
 const[lang,setLang]=useState<Lang>("ru"),[tab,setTab]=useState<Tab>("home"),[balance,setBalance]=useState(10000),[risk,setRisk]=useState("1"),[stop,setStop]=useState("50"),[journal,setJournal]=useState(""),[plan,setPlan]=useState(""),[modal,setModal]=useState<string|null>(null),[lesson,setLesson]=useState(0);
 const t=tx[lang],riskMoney=balance*(Number(risk)||0)/100,lot=Math.max(.01,riskMoney/Math.max(1,Number(stop)||1)/10),progress=Math.round(((lesson+1)/12)*100);
 const trade=(x:number)=>setBalance(v=>Math.max(0,v+x));
 const nav:[Tab,string,string][]=[["home",t.home,"⌂"],["academy",t.academy,"▣"],["terminal",t.terminal,"◈"],["tools",t.tools,"⌁"],["profile",t.profile,"◉"]];
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><View style={s.root}>
 <ScrollView contentContainerStyle={s.content}>
 {tab==="home"&&<><View style={s.header}><View style={{flex:1}}><Text style={s.kicker}>JABORZODA × MUZAFARZODA</Text><Text style={s.title}>TRADE ACADEMY</Text><Text style={s.muted}>{t.sub}</Text></View><Pressable style={s.lang} onPress={()=>setLang(lang==="ru"?"tj":"ru")}><Text style={s.white}>{lang==="ru"?"TJ":"RU"}</Text></Pressable></View>
 <View style={s.hero}><Text style={s.muted}>{t.demo}</Text><Text style={s.balance}>$ {balance.toFixed(2)}</Text><Text style={balance>=10000?s.pos:s.neg}>{balance>=10000?"+":"-"} $ {Math.abs(balance-10000).toFixed(2)}</Text><View style={s.track}><View style={[s.fill,{width:progress+"%"}]}/></View><Text style={s.tiny}>{t.progress}: {progress}%</Text></View>
 <Text style={s.section}>{t.learn}</Text><Pressable style={s.row} onPress={()=>{setLesson(Math.min(lesson+1,11));setModal("lesson")}}><Num n={String(lesson+1).padStart(2,"0")}/><View style={{flex:1}}><Text style={s.white}>{modules[lesson]}</Text><Text style={s.muted}>Lesson • practice • review</Text></View><Text style={s.arrow}>›</Text></Pressable>
 <Text style={s.section}>{t.market}</Text><View style={s.card}><View style={s.between}><Text style={s.white}>EUR/USD</Text><Text style={s.pos}>+0.42%</Text></View><Text style={s.price}>1.17420</Text><Chart/><View style={s.actions}><Pressable style={s.buy} onPress={()=>trade(37.5)}><Text style={s.trade}>{t.buy}</Text></Pressable><Pressable style={s.sell} onPress={()=>trade(-28.4)}><Text style={s.trade}>{t.sell}</Text></Pressable></View></View>
 <View style={s.two}><Pressable style={s.mini} onPress={()=>setTab("tools")}><Text style={s.icon}>◒</Text><Text style={s.white}>{t.risk}</Text></Pressable><Pressable style={s.mini} onPress={()=>setModal("quiz")}><Text style={s.icon}>✓</Text><Text style={s.white}>Quiz</Text></Pressable></View></>}
 {tab==="academy"&&<><Title a={t.academy} b="12 modules • beginner → advanced"/><View style={s.card}><View style={s.between}><Text style={s.white}>{t.progress}</Text><Text style={s.pos}>{progress}%</Text></View><View style={s.track}><View style={[s.fill,{width:progress+"%"}]}/></View></View>{modules.map((m,i)=><Pressable key={m} style={s.row} onPress={()=>{setLesson(i);setModal("lesson")}}><Num n={String(i+1).padStart(2,"0")}/><View style={{flex:1}}><Text style={s.white}>{m}</Text><Text style={s.muted}>{i<=lesson?"Available • practice":"Next module"}</Text></View><Text style={i<=lesson?s.pos:s.lock}>{i<=lesson?"✓":"○"}</Text></Pressable>)}</>}
 {tab==="terminal"&&<><Title a={t.terminal} b="Simulated market • no real money"/><View style={s.card}><View style={s.between}><Text style={s.white}>EUR/USD</Text><Text style={s.pos}>+0.42%</Text></View><Text style={s.price}>1.17420</Text><Chart big/><View style={s.tags}><Tag x="EMA 20"/><Tag x="RSI 14"/><Tag x="MACD"/></View><View style={s.actions}><Pressable style={s.buy} onPress={()=>trade(37.5)}><Text style={s.trade}>{t.buy}</Text></Pressable><Pressable style={s.sell} onPress={()=>trade(-28.4)}><Text style={s.trade}>{t.sell}</Text></Pressable></View></View></>}
 {tab==="tools"&&<><Title a={t.tools} b="Risk, journal and trading plan"/><View style={s.card}><Text style={s.white}>{t.risk}</Text><Field label="Risk %" value={risk} set={setRisk}/><Field label="Stop Loss / points" value={stop} set={setStop}/><Text style={s.result}>Risk: $ {riskMoney.toFixed(2)}</Text><Text style={s.result2}>Lot: {lot.toFixed(2)}</Text></View><Pressable style={s.row} onPress={()=>setModal("journal")}><Num n="J"/><View style={{flex:1}}><Text style={s.white}>{t.journal}</Text><Text style={s.muted}>{journal?"Saved":"Write your trades and conclusions"}</Text></View><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>setModal("plan")}><Num n="P"/><View style={{flex:1}}><Text style={s.white}>{t.plan}</Text><Text style={s.muted}>{plan?"Saved":"Rules for entry, risk and exit"}</Text></View><Text style={s.arrow}>›</Text></Pressable><View style={s.card}><Text style={s.white}>Indicators</Text><View style={s.tags}><Tag x="EMA 20"/><Tag x="EMA 50"/><Tag x="RSI"/><Tag x="MACD"/></View></View></>}
 {tab==="profile"&&<><Title a={t.profile} b={t.author}/><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>JF</Text></View><Text style={s.white}>{t.author}</Text><Text style={s.muted}>TRADE ACADEMY • Mobile</Text><View style={s.line}/><View style={s.between}><Text style={s.muted}>{t.demo}</Text><Text style={s.white}>$ {balance.toFixed(2)}</Text></View><View style={s.between}><Text style={s.muted}>{t.progress}</Text><Text style={s.pos}>{progress}%</Text></View><Pressable style={s.switch} onPress={()=>setLang(lang==="ru"?"tj":"ru")}><Text style={s.white}>{lang==="ru"?"Русский → Тоҷикӣ":"Тоҷикӣ → Русский"}</Text></Pressable></View></>}
 </ScrollView>
 <View style={s.nav}>{nav.map(([id,label,icon])=><Pressable key={id} style={s.navItem} onPress={()=>setTab(id)}><Text style={[s.navIcon,tab===id&&s.active]}>{icon}</Text><Text style={[s.navText,tab===id&&s.active]}>{label}</Text></Pressable>)}</View>
 <Modal visible={modal!==null} transparent animationType="slide" onRequestClose={()=>setModal(null)}><View style={s.overlay}><View style={s.modal}><Text style={s.kicker}>{modal==="lesson"?"LESSON":modal==="quiz"?"QUIZ":modal==="journal"?"JOURNAL":"TRADING PLAN"}</Text>{modal==="lesson"&&<><Text style={s.modalTitle}>{modules[lesson]}</Text><Text style={s.modalText}>{lang==="ru"?"Изучай концепцию, затем проверь её на демо. Главная цель — процесс, риск и дисциплина, а не угадывание следующей свечи.":"Аввал мафҳумро омӯз, баъд дар demo санҷ. Ҳадафи асосӣ раванд, риск ва интизом аст, на тахмин кардани шамъи оянда."}</Text></>}{modal==="quiz"&&<><Text style={s.modalTitle}>{lang==="ru"?"Что ограничивает убыток одной сделки?":"Чӣ зарари як сделкаро маҳдуд мекунад?"}</Text><Pressable style={s.answer} onPress={()=>setModal("lesson")}><Text style={s.white}>Risk Management</Text></Pressable><Pressable style={s.answer} onPress={()=>setModal("lesson")}><Text style={s.white}>Random Entry</Text></Pressable></>}{(modal==="journal"||modal==="plan")&&<><Text style={s.modalTitle}>{modal==="journal"?t.journal:t.plan}</Text><TextInput multiline value={modal==="journal"?journal:plan} onChangeText={modal==="journal"?setJournal:setPlan} placeholder={modal==="journal"?"Setup, entry, SL, TP, result...":"Entry rules, risk, session, exit rules..."} placeholderTextColor="#617068" style={s.area}/></>}<Pressable style={s.primary} onPress={()=>setModal(null)}><Text style={s.primaryText}>DONE</Text></Pressable></View></View></Modal>
 </View></SafeAreaView>;
}
function Title({a,b}:{a:string,b:string}){return <View style={s.titleBlock}><Text style={s.title}>{a}</Text><Text style={s.muted}>{b}</Text></View>}
function Num({n}:{n:string}){return <View style={s.num}><Text style={s.numText}>{n}</Text></View>}
function Tag({x}:{x:string}){return <View style={s.tag}><Text style={s.tagText}>{x}</Text></View>}
function Field({label,value,set}:{label:string,value:string,set:(x:string)=>void}){return <><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType="decimal-pad" style={s.input}/></>}
function Chart({big=false}:{big?:boolean}){return <View style={[s.chart,{height:big?185:105}]}>{candles.map((v,i)=><View key={i} style={s.candle}><View style={[s.wick,{height:v*(big?.5:.3)}]}/><View style={[s.body,{height:Math.max(8,v*(big?.28:.18))}]}/></View>)}</View>}
const s=StyleSheet.create({
safe:{flex:1,backgroundColor:"#050806"},root:{flex:1,backgroundColor:"#050806"},content:{padding:20,paddingBottom:110},
header:{flexDirection:"row",marginBottom:22},kicker:{color:"#6f8d7b",fontSize:10,fontWeight:"900",letterSpacing:2,marginBottom:7},title:{color:"#f2f7f4",fontSize:29,fontWeight:"900"},muted:{color:"#899990",fontSize:13,lineHeight:19},white:{color:"#edf5ef",fontSize:15,fontWeight:"800"},tiny:{color:"#617168",fontSize:10,fontWeight:"700"},
lang:{width:44,height:44,borderRadius:15,borderWidth:1,borderColor:"#294033",alignItems:"center",justifyContent:"center",backgroundColor:"#0b120e",marginLeft:12},
hero:{backgroundColor:"#0d1812",borderRadius:26,padding:22,borderWidth:1,borderColor:"#20372a",marginBottom:22},balance:{color:"#fff",fontSize:38,fontWeight:"900",marginTop:9},pos:{color:"#6fe19a",fontWeight:"900"},neg:{color:"#ff8d8d",fontWeight:"900"},
track:{height:5,backgroundColor:"#1a2920",borderRadius:5,overflow:"hidden",marginTop:15},fill:{height:5,backgroundColor:"#6cdd96",borderRadius:5},section:{color:"#eaf1ed",fontSize:17,fontWeight:"900",marginBottom:10},
row:{flexDirection:"row",alignItems:"center",gap:13,backgroundColor:"#0c1410",borderRadius:18,padding:15,borderWidth:1,borderColor:"#1b2921",marginBottom:10},num:{width:45,height:45,borderRadius:14,backgroundColor:"#153323",alignItems:"center",justifyContent:"center"},numText:{color:"#7ce2a0",fontWeight:"900"},arrow:{color:"#718078",fontSize:28},card:{backgroundColor:"#0c1410",borderRadius:23,padding:19,borderWidth:1,borderColor:"#1b2a21",marginBottom:12},
between:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},price:{color:"#fff",fontSize:35,fontWeight:"900",marginTop:9},chart:{flexDirection:"row",alignItems:"center",gap:4,marginVertical:13,overflow:"hidden"},candle:{flex:1,height:"100%",alignItems:"center",justifyContent:"center"},wick:{width:2,backgroundColor:"#72d99a",position:"absolute",bottom:"16%"},body:{width:"70%",backgroundColor:"#56bd80",borderRadius:2},
actions:{flexDirection:"row",gap:10},buy:{flex:1,backgroundColor:"#17462e",padding:15,borderRadius:15,alignItems:"center"},sell:{flex:1,backgroundColor:"#482326",padding:15,borderRadius:15,alignItems:"center"},trade:{color:"#fff",fontWeight:"900"},two:{flexDirection:"row",gap:10},mini:{flex:1,backgroundColor:"#0d1510",padding:17,borderRadius:19,borderWidth:1,borderColor:"#1c2b22"},icon:{color:"#71dc99",fontSize:23,marginBottom:9},
titleBlock:{marginBottom:20},lock:{color:"#4e5d55",fontWeight:"900"},tags:{flexDirection:"row",gap:7,flexWrap:"wrap",marginTop:12},tag:{backgroundColor:"#14251b",paddingVertical:7,paddingHorizontal:10,borderRadius:10},tagText:{color:"#7fdb9d",fontSize:10,fontWeight:"800"},
label:{color:"#718078",fontSize:11,fontWeight:"800",marginTop:13},input:{color:"#fff",backgroundColor:"#101913",borderRadius:13,padding:13,marginTop:6,borderWidth:1,borderColor:"#24362b"},result:{color:"#6fe19a",fontSize:22,fontWeight:"900",marginTop:16},result2:{color:"#fff",fontSize:20,fontWeight:"900",marginTop:5},
profile:{backgroundColor:"#0c1410",borderRadius:24,padding:23,borderWidth:1,borderColor:"#1c2c22",alignItems:"center"},avatar:{width:76,height:76,borderRadius:25,backgroundColor:"#193c28",alignItems:"center",justifyContent:"center",marginBottom:13},avatarText:{color:"#8aeeb0",fontSize:23,fontWeight:"900"},line:{height:1,backgroundColor:"#1c2a21",width:"100%",marginVertical:20},switch:{marginTop:20,padding:15,borderRadius:15,backgroundColor:"#101913",width:"100%",alignItems:"center"},
nav:{position:"absolute",bottom:0,left:0,right:0,height:80,backgroundColor:"#080e0b",borderTopWidth:1,borderTopColor:"#1a2921",flexDirection:"row",justifyContent:"space-around",paddingTop:9},navItem:{alignItems:"center",width:"20%"},navIcon:{color:"#64726b",fontSize:21,marginBottom:3},navText:{color:"#64726b",fontSize:9,fontWeight:"800"},active:{color:"#78dfa1"},
overlay:{flex:1,backgroundColor:"rgba(0,0,0,.75)",justifyContent:"flex-end"},modal:{backgroundColor:"#101813",padding:24,borderTopLeftRadius:29,borderTopRightRadius:29,borderWidth:1,borderColor:"#26382d"},modalTitle:{color:"#fff",fontSize:25,fontWeight:"900",marginBottom:11},modalText:{color:"#aebbb3",fontSize:15,lineHeight:23,marginBottom:20},answer:{backgroundColor:"#17251c",padding:16,borderRadius:15,marginBottom:9},area:{minHeight:150,color:"#fff",backgroundColor:"#0b120e",borderRadius:15,padding:15,textAlignVertical:"top",borderWidth:1,borderColor:"#24352b"},primary:{backgroundColor:"#6add98",borderRadius:15,padding:15,alignItems:"center",marginTop:16},primaryText:{color:"#061009",fontWeight:"900"}
});